#!/bin/bash
# AUTO-GENERATED by scripts/generate-ensure-binary.sh — DO NOT EDIT
# Source: redit/scripts/ensure-binary.conf + scripts/lib/ensure-binary-lib.sh
set -e

# === Configuration & Hooks ===
BINARY_NAME="redit-mcp"
INSTALL_MODE="local"
VERSION_CHECK="file"
ENABLE_WINDOWS="true"
BUILD_TARGET="./cmd/redit-mcp"

# === Common Logic ===
# Default no-op hooks (overridden by conf if defined before this point)
declare -f hook_pre_install > /dev/null 2>&1 || hook_pre_install() { :; }
declare -f hook_post_install > /dev/null 2>&1 || hook_post_install() { :; }

# --- Setup ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(dirname "$SCRIPT_DIR")"

REPO="bang9/ai-tools"

if [ "$INSTALL_MODE" = "local" ]; then
    INSTALL_DIR="$PLUGIN_ROOT/bin"
else
    INSTALL_DIR="$HOME/.local/bin"
fi
INSTALLED_BINARY="$INSTALL_DIR/$BINARY_NAME"

# --- Expected Version ---
EXPECTED_VERSION=$(grep '"version"' "$PLUGIN_ROOT/.claude-plugin/plugin.json" | head -1 | cut -d'"' -f4)

# --- Version Check ---
if [ "$VERSION_CHECK" = "file" ]; then
    VERSION_FILE="$INSTALL_DIR/.$BINARY_NAME-version"
    if [ -x "$INSTALLED_BINARY" ]; then
        INSTALLED_VERSION=""
        if [ -f "$VERSION_FILE" ]; then
            INSTALLED_VERSION=$(cat "$VERSION_FILE")
        fi
        if [ "$INSTALLED_VERSION" = "$EXPECTED_VERSION" ]; then
            exit 0
        fi
        echo "Upgrading $BINARY_NAME from ${INSTALLED_VERSION:-unknown} to $EXPECTED_VERSION..." >&2
    fi
else
    BINARY_PATH=""
    if command -v "$BINARY_NAME" &> /dev/null; then
        BINARY_PATH="$(command -v "$BINARY_NAME")"
    elif [ -x "$INSTALLED_BINARY" ]; then
        BINARY_PATH="$INSTALLED_BINARY"
    fi
    if [ -n "$BINARY_PATH" ]; then
        INSTALLED_VERSION=$("$BINARY_PATH" --version 2>/dev/null | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' || echo "")
        if [ "$INSTALLED_VERSION" = "$EXPECTED_VERSION" ]; then
            exit 0
        fi
        echo "Upgrading $BINARY_NAME from ${INSTALLED_VERSION:-unknown} to $EXPECTED_VERSION..." >&2
    fi
fi

mkdir -p "$INSTALL_DIR"

# --- Platform Detection ---
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"

case "$ARCH" in
    x86_64) ARCH="amd64" ;;
    aarch64|arm64) ARCH="arm64" ;;
    *) echo "Unsupported architecture: $ARCH" >&2; exit 1 ;;
esac

if [ "$ENABLE_WINDOWS" = "true" ]; then
    case "$OS" in
        darwin|linux) ;;
        mingw*|msys*|cygwin*) OS="windows" ;;
        *) echo "Unsupported OS: $OS" >&2; exit 1 ;;
    esac
else
    case "$OS" in
        darwin|linux) ;;
        *) echo "Unsupported OS: $OS" >&2; exit 1 ;;
    esac
    case "${OS}-${ARCH}" in
        darwin-arm64|darwin-amd64|linux-amd64) ;;
        *) echo "Unsupported platform: ${OS}/${ARCH}. Supported: darwin/arm64, darwin/amd64, linux/amd64" >&2; exit 1 ;;
    esac
fi

# --- Download Setup ---
VERSION="$EXPECTED_VERSION"
DOWNLOAD_NAME="${BINARY_NAME}-${OS}-${ARCH}"
if [ "$OS" = "windows" ]; then
    DOWNLOAD_NAME="${DOWNLOAD_NAME}.exe"
    INSTALLED_BINARY="${INSTALLED_BINARY}.exe"
fi
DOWNLOAD_URL="https://github.com/${REPO}/releases/download/${VERSION}/${DOWNLOAD_NAME}"

# --- Pre-install Hook ---
hook_pre_install

echo "Downloading $BINARY_NAME ${VERSION}..." >&2

# --- safe_install ---
safe_install() {
    local url="$1" dest="$2" tmp="${dest}.tmp.$$"
    if curl -fsSL -o "$tmp" "$url"; then
        chmod +x "$tmp"
        rm -f "$dest"
        mv "$tmp" "$dest"
        return 0
    fi
    rm -f "$tmp"
    return 1
}

# --- record_version (file-based version tracking) ---
record_version() {
    if [ "$VERSION_CHECK" = "file" ]; then
        echo "$VERSION" > "$VERSION_FILE"
    fi
}

# --- Download & Install ---
if command -v curl &> /dev/null; then
    if safe_install "$DOWNLOAD_URL" "$INSTALLED_BINARY"; then
        record_version
        echo "$BINARY_NAME ${VERSION} installed to $INSTALLED_BINARY" >&2
        hook_post_install
        exit 0
    fi
elif command -v wget &> /dev/null; then
    TMP_BINARY="${INSTALLED_BINARY}.tmp.$$"
    if wget -q -O "$TMP_BINARY" "$DOWNLOAD_URL"; then
        chmod +x "$TMP_BINARY"
        rm -f "$INSTALLED_BINARY"
        mv "$TMP_BINARY" "$INSTALLED_BINARY"
        record_version
        echo "$BINARY_NAME ${VERSION} installed to $INSTALLED_BINARY" >&2
        hook_post_install
        exit 0
    fi
    rm -f "$TMP_BINARY"
fi

echo "Failed to download binary. Trying to build from source..." >&2

# --- Build from Source ---
if command -v go &> /dev/null; then
    echo "Building $BINARY_NAME from source..." >&2
    cd "$PLUGIN_ROOT"
    go build -o "$INSTALLED_BINARY" "$BUILD_TARGET"
    record_version
    echo "$BINARY_NAME built successfully" >&2
    exit 0
fi

echo "Error: Could not download binary and Go is not installed." >&2
echo "Please install Go or download manually from:" >&2
echo "  ${DOWNLOAD_URL}" >&2
exit 1
